Add support for reverting ovs2ovn migration
While the upstream patch [1] is still WIP we would like to have
ability to early test it with our downstream code.
This patch adds the following:
- tasks to inject code from a specific patch set of [1].
  Note: [1] adds tasks for preparing and performing backup of
  controller nodes by means of ReaR tool. See [2] for details.
- tasks to restore controller nodes to the point before ovs2ovn
  migration.
  Note: restore_controllers.yml was taken almost completely as is
  from [3]. Just minor changes were introduced in order to fit
  ovn migration plugin code.
- 'revert' role that executes 'revert' playbook from [1] and
  does overcloud update afterwards.
- validations code changes to support 2 modes, ovn and ovs.
- various cosmetic changes to organise code, removed redundant
  leftovers.

[1] https://review.opendev.org/c/openstack/neutron/+/835638
[2] https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.2/html/backing_up_and_restoring_the_undercloud_and_control_plane_nodes/assembly_backing-up-the-control-plane-nodes_br-undercloud-ctlplane
[3] https://gitlab.cee.redhat.com/osp-dfg-enterprise/ir_backup-and-restore/-/blob/master/playbooks/05-restore-controllers.yaml

Change-Id: I23e9d967b84fdd0a1faa221424dad09747bb1935

diff --git a/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-pinger.sh.j2 b/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-pinger.sh.j2
--- a/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-pinger.sh.j2
+++ b/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-pinger.sh.j2
@@ -4,6 +4,7 @@ set -x
 resources_type={{ resources_type }}
 server_user_name={{ server_user_name }}
 packet_loss_threshold={{ packet_loss_threshold }}
+validations_type=$1
 
 check_if_pinger_stopped(){
     [ "$2" == "quick" ] && wait_time=1 || wait_time=10
@@ -28,42 +29,73 @@ validate(){
     echo "$1: Passed validation"
 }
 
-echo TEST: test_ping_to_workload_fips
-file_list=`ls {{ ovn_migration_temp_dir }}/*ping.out`
-[ "$file_list" == "" ] && echo "FAIL: No pinger log files found. Something went wrong." && exit
 
-for file in $file_list; do
-    check_if_pinger_stopped $file
-    validate $file
-done
-echo PASS: test_ping_to_workload_fips
-
-if [[ "$resources_type" =~ "trunk" ]]; then
-    echo TEST: test_ping_between_trunk_subports
-
-    if [ "{{ shutdown_workload }}" == "True" ]; then
-        for fip in `cat {{ ovn_migration_temp_dir }}/trunk_vms_fips`; do
-            ips=$(timeout 10 ssh $server_user_name@$fip ls ping_*_output | sed 's/.*_\(.*\)_.*/\1/')
-            for ip in $ips; do
-                timeout 10 ssh $server_user_name@$fip  "ping $ip > ping_${ip}_output 2>&1 &"
-            done
-        done
-	sleep 60
-    fi
-
-    for fip in `cat {{ ovn_migration_temp_dir }}/trunk_vms_fips`; do
-	timeout 10 ssh $server_user_name@$fip pkill --signal SIGINT ping
-	sleep 2
-	mkdir -p {{ ovn_migration_temp_dir }}/ping_output/$fip
-        timeout 10 scp "$server_user_name@$fip:ping_*_output" {{ ovn_migration_temp_dir }}/ping_output/$fip
-    done
-
-    file_list=`find {{ ovn_migration_temp_dir }}/ping_output -type f`
+if [ "$validations_type" == "ovn_migration_validations" ]; then
+    echo TEST: test_workload_vms_downtime
+    file_list=`ls {{ ovn_migration_temp_dir }}/*ping.out`
     [ "$file_list" == "" ] && echo "FAIL: No pinger log files found. Something went wrong." && exit
 
     for file in $file_list; do
-        check_if_pinger_stopped $file quick
+        check_if_pinger_stopped $file
         validate $file
     done
-    echo PASS: test_ping_between_trunk_subports
+    echo PASS: test_workload_vms_downtime
+
+    if [[ "$resources_type" =~ "trunk" ]]; then
+        echo TEST: test_trunk_subports_downtime
+
+        if [ "{{ shutdown_workload }}" == "True" ]; then
+            for fip in `cat {{ ovn_migration_temp_dir }}/trunk_vms_fips`; do
+                ips=$(timeout 10 ssh $server_user_name@$fip ls ping_*_output | sed 's/.*_\(.*\)_.*/\1/')
+                for ip in $ips; do
+                    timeout 10 ssh $server_user_name@$fip  "ping $ip > ping_${ip}_output 2>&1 &"
+                done
+            done
+        sleep 60
+        fi
+
+        for fip in `cat {{ ovn_migration_temp_dir }}/trunk_vms_fips`; do
+            timeout 10 ssh $server_user_name@$fip pkill --signal SIGINT ping
+            sleep 2
+            mkdir -p {{ ovn_migration_temp_dir }}/ping_output/$fip
+            timeout 10 scp "$server_user_name@$fip:ping_*_output" {{ ovn_migration_temp_dir }}/ping_output/$fip
+        done
+
+        file_list=`find {{ ovn_migration_temp_dir }}/ping_output -type f`
+        [ "$file_list" == "" ] && echo "FAIL: No pinger log files found. Something went wrong." && exit
+
+        for file in $file_list; do
+            check_if_pinger_stopped $file quick
+            validate $file
+        done
+        echo PASS: test_trunk_subports_downtime
+    fi
+fi
+
+if [ "$validations_type" == "ovn_migration_revert_validations" ]; then
+    echo TEST: test_workload_vms_connectivity
+    [ ! -e {{ ovn_migration_temp_dir }}/server_fips ] && echo "FAIL: File with VM addresses not found. Something went wrong." && exit
+    while read ip; do
+        ping -c 3 $ip
+        if [ $? -ne 0 ]; then
+            echo "FAIL: No response from $ip" && exit
+        fi
+    done < "{{ ovn_migration_temp_dir }}/server_fips"
+    echo PASS: test_workload_vms_connectivity
+
+    if [[ "$resources_type" =~ "trunk" ]]; then
+        echo TEST: test_trunk_subports_connectivity
+        [ ! -e {{ ovn_migration_temp_dir }}/trunk_vms_fips ] && echo "FAIL: File with VM addresses not found. Something went wrong." && exit
+        for fip in `cat {{ ovn_migration_temp_dir }}/trunk_vms_fips`; do
+            ips=$(timeout 10 ssh $server_user_name@$fip ls ping_*_output | sed 's/.*_\(.*\)_.*/\1/')
+            for ip in $ips; do
+                timeout 10 ssh $server_user_name@$fip ping -c 3 $ip
+                if [ $? -ne 0 ]; then
+                    echo "FAIL: Subport connectivity test failed."
+                    exit
+                fi
+            done
+        done
+        echo PASS: test_trunk_subports_connectivity
+    fi
 fi
