Support granular_poc workload in ovs2ovn validations
granular_poc workload uses 2 availability zones each with 2 internal
networks. This patch changes validations to support this.

Change-Id: I7abc352b452b8733790ce20143182e0456466075

diff --git a/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-network.sh.j2 b/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-network.sh.j2
--- a/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-network.sh.j2
+++ b/ovn_migration/infrared/tripleo-ovn-migration/roles/create-resources/templates/validate-network.sh.j2
@@ -3,14 +3,31 @@ set -x
 
 . {{ overcloudrc }}
 resources_type={{ resources_type }}
+
 echo TEST: test_network_is_geneve
 if ( [[ "$resources_type" =~ "sriov" ]] || [[ "$resources_type" =~ "ext" ]] ) && ! [ "$resources_type" == "trunk_ext_with_normal_int" ] && ! [ "$resources_type" == "normal_ext_int" ]; then
     echo "SKIPPED: This workload type does not create a network that migrates to geneve. Skipping the check."
     exit
 fi
-network_type=$(openstack network show ovn-migration-net-{{ resource_suffix }} -c provider:network_type -f value)
-if [ "$network_type" == "geneve" ]; then
-    echo "PASS: Network type changed successfully to 'geneve' after migration."
+
+check_network_type_is_geneve(){
+  if [ "$1" == "geneve" ]; then
+    return 0
+  else
+    return 1
+  fi
+}
+result=pass
+networks=$(openstack network list --internal -c ID -c Name -f value | grep migration | awk '{print $1}')
+
+for net in $networks;do
+  network_type=$(openstack network show $net -c provider:network_type -f value)
+  check_network_type_is_geneve $network_type
+  [ $? -ne 0 ] && result=fail && break
+done
+
+if [ "$result" == "fail" ]; then
+  echo "FAIL: Workload network with type other than 'geneve' found"
 else
-    echo "FAIL: Network type is '$network_type' while expected value is 'geneve'."
+  echo "PASS: All workload networks changed successfully to 'geneve' after migration."
 fi
